### ISSUE TITLE
Any map not in the database 

### ISSUE THREAD

**Issue by oSumAtrIX** [LeaPhant/flowabot#12]
The bot always says, that the maps are not in the database. I provided my api key and the bot is running fine

**Comment by LeaPhant** [comment]
You might be running Node.js <10, check with `node --version`. Node.js 10 or higher is required, probably the same issue as #5.

**Comment by oSumAtrIX** [comment]
After updating Node to v10 I receive the same error message 
https://i.imgur.com/rPcGf0K.png

**Comment by LeaPhant** [comment]
Oh, that's weird. Can you tell me the beatmap id of the map you're trying and your `beatmap_api` value in `config.json`?

**Comment by oSumAtrIX** [comment]
The `beatmap_api` value is the same as my osu API key, therefore I can't share it here, also no beatmap does work including the beatmaps given here https://github.com/LeaPhant/flowabot/blob/master/COMMANDS.md#pp

**Comment by oSumAtrIX** [comment]
Fixed.
