### ISSUE TITLE
Implement cursor interpolation for replay rendering

### ISSUE THREAD

**Issue by TheOmyNomy** [LeaPhant/flowabot#13]
Replays that use the "30fps replay system" (before ~March 2014) have noticeable skips in cursor movement. Implementing cursor interpolation between frames would resolve this issue.

Example: rrtyui's HDDT score on https://osu.ppy.sh/beatmapsets/43003#osu/139634.

**Comment by LeaPhant** [comment]
Added in https://github.com/LeaPhant/flowabot/commit/c6f7f8e4dc92b05cb9ce2df49718337f431fa881. Thanks for the suggestion!
