### ISSUE TITLE
ffmpeg not found by default

### ISSUE THREAD

**Issue by oSumAtrIX** [LeaPhant/flowabot#15]
No binary of ffmpeg is beeing provided when setting up flowabot 
https://i.imgur.com/pr4HpXO.png
You might add that to your readme

**Comment by LeaPhant** [comment]
The ffmpeg binary should be provided by the [ffmpeg-static](https://github.com/eugeneware/ffmpeg-static) module, although I haven't tested it on ARM. Since you had another module error in the other issue maybe remove the `node_modules` folder an do `npm i` again.

**Comment by lurr** [comment]
The binaries for ARM seem to have been added in commit eugeneware/ffmpeg-static@786ca8daf8e985fc3b906e81e81374d7dd3b0c6e, which may fix the issue. Should be as simple as updating the dependency to `2.5.0`, hopefully.
