### ISSUE TITLE
UnhandledPromiseRejectionWarning on render

### ISSUE THREAD

**Issue by Maaster** [LeaPhant/flowabot#17]
Having 
>https://osu.ppy.sh/beatmapsets/923095#osu/1927666

as the recent score and running
>render strains 10s

results in no output in Discord and this error in the server console

>[2019-07-14T05:38:46.785Z] Maaster : !render strains 10s
[2019-07-14T05:38:46.785Z] render length 10
[2019-07-14T05:38:46.785Z] specified ar undefined
(node:28054) UnhandledPromiseRejectionWarning: Couldn't download file
(node:28054) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)

**Comment by LeaPhant** [comment]
Fixed in https://github.com/LeaPhant/flowabot/commit/8e7c38ab79011ead257f9c73edd0ccfda80bcb4b. Thanks for reporting!
