### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by zivoy** [LeaPhant/flowabot#23]
I am running the bot on a GCP instance that has only 600mbs of ram.
The bot works for the most part and most things render fine but problems occur when rendering long death streams, the bot uses up all the ram and takes a long time to render.
this doesn't happen when rendering normal things like jumps or a regular streams and sliders.

--ziv

**Comment by LeaPhant** [comment]
Rendering beatmaps just requires a lot of memory. Beatmap Objects can use 100 MB of memory for maps with a lot of objects and that's for every render thread (one per cpu thread) cause I don't think I can share it. I don't know how I can improve this in the future cause Node.js has limited control in this regard and I'm also not well-versed in this kind of optimization.

If you have a specific map where you think there could be a memory leak send it to me, cause I've tested some and memory usage scales with the amount of hit objects.
