### ISSUE TITLE
Timestamp on recent score is wrong

### ISSUE THREAD

**Issue by Maaster** [LeaPhant/flowabot#24]
Maybe a timezone error? 
>!rs

is returning "in an hour" for the time that play was made

See: https://puu.sh/DUstw/28b1ba4960.png

**Comment by LeaPhant** [comment]
Weird, I've never had this happen and the API usually returns UTC timestamps. Maybe a bug from Moment.js? What you could do is check whether running `date` on the server matches your local time and maybe it doesn't which *could* cause the bug, although it shouldn't.

**Comment by Maaster** [comment]
I feel dumb, that was it! 
Thanks :)
