### ISSUE TITLE
!viewers command broken - Bad HTTP request | error 400

### ISSUE THREAD

**Issue by oSumAtrIX** [LeaPhant/flowabot#25]
The parameter "id" was malformed: the value must match the regular expression /^[0-9]+$/
https://i.imgur.com/k7AEVB5.png

**Comment by LeaPhant** [comment]
Ugh, this is the same stuff I had in my other project with newer Client IDs acting different than older Client IDs. I will have to change to Twitch's Helix API which is more delayed.

**Comment by LeaPhant** [comment]
Fixed in https://github.com/LeaPhant/flowabot/commit/04b4b40a7e0e99d9b7c8a60d636aea1e88796afb. Also gave it a nice embed preview with this commit. :)

![Screenshot_2019-07-30_21-27-42](https://user-images.githubusercontent.com/14080165/62158936-e2f3fc00-b310-11e9-8f8b-e1a6ab0a4dae.png)
