### ISSUE TITLE
Error occurs on Aspire winner 2018's map

### ISSUE THREAD

**Issue by oSumAtrIX** [LeaPhant/flowabot#26]
https://i.imgur.com/QJVP6Ow.png

**Comment by LeaPhant** [comment]
Yep, maps like these definitely won't work for now. I tried preventing a crash when these are processed but I couldn't manage to do as it crashes on V8 engine level. The best is to just run it with pm2 so it restarts on a crash for now.

**Comment by nekoraw** [comment]
https://nekoraw.s-ul.eu/BUqOonOy

doesn't crash anymore
it actually rendered the map

https://nekoraw.s-ul.eu/n25iSzab
