### ISSUE TITLE
overlapping circles with low stack leniency

### ISSUE THREAD

**Issue by nekoraw** [LeaPhant/flowabot#28]
![image](https://user-images.githubusercontent.com/50468652/63204761-8feca980-c071-11e9-95c7-f7d8ffa03769.png)

rendering speed generates this video:
https://cdn.discordapp.com/attachments/383670913469513729/612087996031827989/video.mp4

saw this with other maps before but im too lazy to remember which maps have a low stack leniency

**Comment by nekoraw** [comment]
this is how the map really is: https://streamable.com/guudw

**Comment by LeaPhant** [comment]
Sorry for being so late I haven't looked into this project for a while! I copied the stacking algorithm from somewhere else cause I didn't really understand it myself but I'll look into it and try to fix this inaccuracy.

**Comment by LeaPhant** [comment]
Finally got around to porting the osu!lazer stacking algorithm, this is fixed now! https://github.com/LeaPhant/flowabot/commit/a7dbe80f5cd2efb0c4237aef699ccf46ae7494c7
