### ISSUE TITLE
difficulty bar graph is a bit off

### ISSUE THREAD

**Issue by zivoy** [LeaPhant/flowabot#29]
This issue is a bit more prominent in shorter maps
![image](https://user-images.githubusercontent.com/16857861/63327810-ecafc480-c2fc-11e9-9627-43afcf27a16a.png)

Problem:
https://github.com/LeaPhant/flowabot/blob/528a5fcd1461c45f715b46e946dd7eb579d1b30b/osu.js#L1633
Solution:
```javascript
let x = (index + 1) / strain_chunks.length * 399;
```

**Comment by LeaPhant** [comment]
Sorry for the late reply, I haven't looked into this project for a while. This totally should be `index + 1`, you're right. I've never been good with these edge cases. :smile: 

Fixed in https://github.com/LeaPhant/flowabot/commit/52ab03c10b05402714935a8698b96d57235f5374, thanks a lot!
