### ISSUE TITLE
AR way too high when rendering DT videos.

### ISSUE THREAD

**Issue by nekoraw** [LeaPhant/flowabot#34]
let's use [this](https://nekoraw.s-ul.eu/BCSR3JZm) play as example
[render video](https://cdn.discordapp.com/attachments/653325692666118158/662494604410486814/video.mp4)
[in-game video](https://streamable.com/zwj7z)

as you can tell, this AR is way too high compared to a normal 10.3

**Comment by LeaPhant** [comment]
Seems like AR changes were applied twice with speed-changing mods. Once calculated and then again due to speeding up or slowing down the beatmap during rendering. Fixed in https://github.com/LeaPhant/flowabot/commit/7389af14775a8f771e6dfc5c38e8eab3edc09606, thanks for reporting!
