### ISSUE TITLE
(feature) !top command showing top 5 scores instead of just top #1 score?

### ISSUE THREAD

**Issue by maxerium** [LeaPhant/flowabot#35]
As the title states it, adding that functionality, perhaps under a different command would be quite nice since it would mimic the !top feature of owo!, since well, most people are used to that response/behavior. Would make swapping out owo! with a self-hosted flowabot way smoother/nicer.

**Comment by LeaPhant** [comment]
I started work for this in a branch ([add-tops-command](https://github.com/LeaPhant/flowabot/tree/add-tops-command)) a while ago but I need to add batch beatmap requesting to my api first so I can get the beatmap info of all maps in one request.

**Comment by LeaPhant** [comment]
Added via new !tops command that displays top 5 scores. You can also specify a custom amount like this `!tops7 peppy`.
