### ISSUE TITLE
a way to limit max !render length

### ISSUE THREAD

**Issue by shrublet** [LeaPhant/flowabot#37]
I'm sure it's not too difficult to implement, I'm just mega stupid :( Would be great since personally I've been running this off a very low-powered web server so bandwidth is small and the bot totally hangs if people try to render more than 10 seconds.

**Comment by LeaPhant** [comment]
You could the following code into this line https://github.com/LeaPhant/flowabot/blob/master/commands/render.js#L142:

```JS
length = Math.min(length, 10);
```

This will force the length to not go above 10 seconds. :)

**Comment by JuanM4T** [comment]
> You could insert the following code into this line https://github.com/LeaPhant/flowabot/blob/master/commands/render.js#L142:
> 
> ```js
> length = Math.min(length, 10);
> ```
> 
> This will force the length to not go above 10 seconds. :)
it doesn't work for me like that. I don't know if I've done it wrong, but it won't work.
![image](https://user-images.githubusercontent.com/52723130/102718994-9afdbc80-42eb-11eb-895b-1bc1bfe3377a.png)

**Comment by nekoraw** [comment]
> > You could insert the following code into this line https://github.com/LeaPhant/flowabot/blob/master/commands/render.js#L142:
> > ```js
> > length = Math.min(length, 10);
> > ```
> > 
> > 
> > This will force the length to not go above 10 seconds. :)
> 
> it doesn't work for me like that. I don't know if I've done it wrong, but it won't work.
> ![image](https://user-images.githubusercontent.com/52723130/102718994-9afdbc80-42eb-11eb-895b-1bc1bfe3377a.png)

workaround:

change `length = parseFloat(arg);` to `length = Math.min(parseFloat(arg),60);` in line 117 on commands/render.js
dont forget to change 60 to any value you want in seconds

![image](https://user-images.githubusercontent.com/50468652/103576461-f0bc9200-4eb1-11eb-9074-e28a7415c03e.png)

![image](https://user-images.githubusercontent.com/50468652/103576436-e4383980-4eb1-11eb-9a8b-d3ee7925c6b3.png)

![image](https://user-images.githubusercontent.com/50468652/103576255-9fac9e00-4eb1-11eb-855a-b1ffe6dfd02e.png)

**Comment by JuanM4T** [comment]
thank you! it worked alright!
