### ISSUE TITLE
Rendering judgements (100s, 50s, misses)

### ISSUE THREAD

**Issue by shrublet** [LeaPhant/flowabot#39]
Hi! Just wanted to know if there's any possibility of adding the ability to render judgements as it's helpful when used to show a recent play. Thanks in advanced and have enjoyed using the bot over the past few months! :)

edit solved prev questions nvmnvm

**Comment by LeaPhant** [comment]
This is in now with the newest version, there's still a few mismatches but I'll work on making it more accurate.
