### ISSUE TITLE
!strains graph hard to view

### ISSUE THREAD

**Issue by nekoraw** [LeaPhant/flowabot#43]
it is hard to see the graph because it's being rendered with a part of the map in front of it.
![IMG_20201220_075354.jpg](https://user-images.githubusercontent.com/50468652/102711521-12563080-4299-11eb-91d4-bc280b0cf178.jpg)

I'm running on Arch Linux with the nodejs-lts-dubnium package.

**Comment by LeaPhant** [comment]
Made the opacity of the beatmap lower in https://github.com/LeaPhant/flowabot/commit/825ee888caf113e4285fad96f5777e0dcab12f7e. Thanks for reporting. :)
