### ISSUE TITLE
NC doesnt get recognized as DT

### ISSUE THREAD

**Issue by JuanM4T** [LeaPhant/flowabot#47]
When doing !render +NC, or when doing !render to a play with NC it will displays as if NC wasn't anything.
![image](https://user-images.githubusercontent.com/52723130/104110078-7d14ed80-52d4-11eb-8583-58166bf3b6b2.png)
![image](https://user-images.githubusercontent.com/52723130/104110093-94ec7180-52d4-11eb-9639-99c1193f7da9.png)

**Comment by LeaPhant** [comment]
Fixed in https://github.com/LeaPhant/flowabot/commit/d266dcfa8eb892152bf83619f95ca22da44a2db5. 
Better late than never :')

Thanks for reporting!
