### ISSUE TITLE
discord.js@12.5.1 is incompatible with nodejs<12.0.0 and flowabot needs lts-dubnium(10.x.x) to run

### ISSUE THREAD

**Issue by nekoraw** [LeaPhant/flowabot#49]
![image](https://user-images.githubusercontent.com/50468652/107653833-d15b1680-6c60-11eb-8dcd-5710f199265a.png)
![image](https://user-images.githubusercontent.com/50468652/107653919-e9329a80-6c60-11eb-9192-2b617533155f.png)

updating to nodejs-jts-erbium (12.x.x) solves this problem but the bot does not start anymore

![image](https://user-images.githubusercontent.com/50468652/107654352-58a88a00-6c61-11eb-9390-144dfed7e19e.png)

[2021-02-11T15_04_10_729Z-debug.log](https://github.com/LeaPhant/flowabot/files/5966285/2021-02-11T15_04_10_729Z-debug.log)

same thing with latest nodejs version
tried reinstalling the bot but the error persists

**Comment by LeaPhant** [comment]
It's a mess right now, some dependencies break on nodejs >10 but using an outdated discord.js version brings other problems. I'm in the process of rewriting some code to make everything work on nodejs 14+ and make use of the new features. To make it work right now you can force using discord.js 11 by running `npm i discord.js@11`.

**Comment by LeaPhant** [comment]
I pushed a ton of changes over the last 2 days which now make it default to Discord.js 12 and will make it run Node.js 14 and up, you should try again. :)
