### ISSUE TITLE
y no work

### ISSUE THREAD

**Issue by Jerrynicki** [LeaPhant/flowabot#5]
https://i.imgur.com/T3j0DKy.png peppy pls fix

**Comment by LeaPhant** [comment]
Could you give me the console output when you run the command? (with debug enabled in config)

**Comment by LeaPhant** [comment]
Did you by any chance play this map before you ran the command? https://osu.ppy.sh/beatmapsets/949515#osu/2018883

**Comment by M3IY0U** [comment]
Hi, I'm actually the guy who hosted and tried to run the command in the picture, this is what the console output is: 
![image](https://user-images.githubusercontent.com/8927997/61048222-8e302600-a3e1-11e9-829f-0ecb82909cce.png)

**Comment by LeaPhant** [comment]
Oh, you will need Node.js 10 or higher for the bot to work, preferrably 10 LTS. This should fix it. 
Be sure to `rm -r node_modules && npm i` in the bot folder after upgrading Node.

**Comment by LeaPhant** [comment]
I'll close this for now since I haven't gotten any feedback.
