### ISSUE TITLE
Can't use Twitch Client ID

### ISSUE THREAD

**Issue by xDololow** [LeaPhant/flowabot#55]
So basically when I try to add Twitch Client ID it says not valid id. It either twitch being bithx or something updated in api and its not working.
Me trying:
![image](https://user-images.githubusercontent.com/26763912/114750460-3543ad80-9d7e-11eb-96f1-10d5bbaf5e23.png)

**Comment by LeaPhant** [comment]
The Twitch API version being used is deprecated so the check broke. For now you can manually enter a client id in `config.json` and the Twitch commands will work until I get around to updating it.

```JSON
{
  "credentials": {
    "twitch_client_id": "4828482",
    ...
  }
}```
