### ISSUE TITLE
API Key is apparently invalid, any clue as to why?

### ISSUE THREAD

**Issue by Adnaval1** [LeaPhant/flowabot#6]
![image](https://user-images.githubusercontent.com/31361852/61016164-add13b00-a35c-11e9-98fc-cafe739c49ff.png)
![image](https://user-images.githubusercontent.com/31361852/61016220-e07b3380-a35c-11e9-93a3-e6ff65398f97.png)

**Comment by Adnaval1** [comment]
Some commands are also giving me 401 errors. I'm certain that my API's are valid from the osu!api page. Help would be appreciated.

**Comment by LeaPhant** [comment]
Have you tried generating a new API key? Maybe it was disabled.

**Comment by Adnaval1** [comment]
Generated an API key twice.

**Comment by LeaPhant** [comment]
Did you check if the correct api key is in `config.json`? Cause if it is and it still doesn't work I'm clueless about why it would happen.

**Comment by Adnaval1** [comment]
Fixed it, I don't know why but I had to make 3 API's for it to work. 3rd times the charm haha.

**Comment by LeaPhant** [comment]
Glad to hear it works :)
