### ISSUE TITLE
[Bug] !render in channel that flowabot has never spoken in returns help prompt

### ISSUE THREAD

**Issue by shrublet** [LeaPhant/flowabot#61]
Since flowabot has no last map to pull from in a channel it's never messaged, using !render will always return the help prompt regardless if a link is supplied with it (I think because it checks for previous map first?). I was scratching my head the first time this happened and then realized it was for this reason with subsequent testing.

**Comment by xDololow** [comment]
This also affects other commands like strains, pp and ect.

**Comment by Woctor-Dho** [comment]
Any progress on this issue? I cant get the bot to work because of this behavior.

**Comment by Woctor-Dho** [comment]
Is there a resolution or workaround for this? I am also having this issue. All commands result in the help prompt

**Comment by shrublet** [comment]
> Is there a resolution or workaround for this? I am also having this issue. All commands result in the help prompt

You should be able to just run `!recent` or any other command that doesn't  try and search for a previous map first.
