### ISSUE TITLE
(Windows) Bot fails to start

### ISSUE THREAD

**Issue by davson19** [LeaPhant/flowabot#7]
http://prntscr.com/odeoyo

**Comment by davson19** [comment]
Not sure what to say other than what's already in the pic, I (think) all the dependencies are installed, although I did get a few errors trying to install everything, that's shown here: http://prntscr.com/odeqd5

**Comment by Jouveer** [comment]
Try #9 
Those npm warnings can be ignored.

**Comment by LeaPhant** [comment]
Yes, please use the guide in #9 to run the bot in WSL.
