### ISSUE TITLE
Bot link to replay video being sent as text, not hyperlink

### ISSUE THREAD

**Issue by xDololow** [LeaPhant/flowabot#71]
So the link that bot returns being sent as text, bot hyperlinking. Copy and pasting message work fine.
![image](https://github.com/user-attachments/assets/128872e1-1a2a-42ac-b709-c8db9ee80a72)

My upload_command looks like this: `curl -X POST -F \"token=token_xxxxxxxxxxxxxxxxx\" -F \"file=@{path}\" http://127.0.0.1:8081/upload | grep -oP '\"raw_url\":\"\\K[^\"]+' ` (I have grep cuz xBackbone returns json like this `{"message":"OK","version":"3.7.0","url":"https://files.xxxd.org/revo1/DeBIMaxU58.mp4","raw_url":"https://files.xxxd.org/revo1/DeBIMaxU58/raw.mp4"}`)

**Comment by LeaPhant** [comment]
I can't seem to reproduce this but it might be the ascii control characters by grep's formatter causing it. I'd recommend trying jq with `curl ... | jq -r .raw_url`.

**Comment by xDololow** [comment]
> I can't seem to reproduce this but it might be the ascii control characters by grep's formatter causing it. I'd recommend trying jq with `curl ... | jq -r .raw_url`.

Yep, jq worked.
That's how it looked with grep 
![image](https://github.com/user-attachments/assets/c568c02a-f779-4155-85a3-425efb37447d)

**Comment by LeaPhant** [comment]
https://github.com/LeaPhant/flowabot/commit/794c53821a89d1ef00ec427774405bec1b212a63 Took the opportunity to actually validate the URL which seems to also get rid of the control characters, shouldn't happen anymore with grep either.
